import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Sparkles, Loader2, Zap, RefreshCw } from "lucide-react";

const TONES = [
  { name: "Cosmic",     icon: "🌌", desc: "Space & nebula themes" },
  { name: "Bio-Digital",icon: "🧬", desc: "DNA & cellular themes" },
  { name: "Cyber-Punk", icon: "⚡", desc: "Neon & glitch themes" },
  { name: "Quantum",    icon: "⚛️",  desc: "Particle & wave themes" },
  { name: "Abstract",   icon: "🔷", desc: "Geometric & math themes" },
];

const TONE_PROMPTS = {
  "Cosmic":     "futuristic cosmic nebula space NFT, dark purple and cyan, stars, galaxy spiral, QVTX blockchain theme, digital art",
  "Bio-Digital":"DNA double helix NFT, bioluminescent green and cyan cells, microscopic digital organism, QVTX blockchain aesthetic",
  "Cyber-Punk": "neon cyberpunk NFT glitch art, magenta and cyan on black, circuit board patterns, QVTX digital token",
  "Quantum":    "quantum particle wave interference NFT, abstract physics visualization, cyan gold on dark, QVTX energy field",
  "Abstract":   "abstract geometric mathematical NFT, sacred geometry patterns, gold and cyan gradient, QVTX digital art",
};

function generateDNA(seed = "") {
  const bases = "ATCG";
  let dna = "";
  const hash = [...seed].reduce((a, c) => a + c.charCodeAt(0), Date.now());
  for (let i = 0; i < 32; i++) dna += bases[(hash * (i + 1) * 31337) % 4 | 0];
  return dna;
}
function generateByteId(str = "") {
  let h = 0xdeadbeef;
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 2654435761);
  return "0x" + ((h >>> 0).toString(16).padStart(8, "0")).toUpperCase();
}

const RARITIES = ["COMMON", "RARE", "EPIC", "LEGENDARY", "MYTHIC"];
const RARITY_WEIGHTS = [50, 30, 12, 6, 2];

function weightedRarity() {
  const r = Math.random() * 100;
  let sum = 0;
  for (let i = 0; i < RARITIES.length; i++) {
    sum += RARITY_WEIGHTS[i];
    if (r < sum) return RARITIES[i];
  }
  return "COMMON";
}

export default function AutoMakePanel({ user, onGenerated }) {
  const [settings, setSettings] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [settingsId, setSettingsId] = useState(null);

  useEffect(() => {
    if (!user?.id) return;
    loadSettings();
  }, [user?.id]);

  const loadSettings = async () => {
    setLoading(true);
    const all = await base44.entities.NFTAutoMakeSettings.filter({ userId: user.id });
    if (all.length > 0) {
      setSettings(all[0]);
      setSettingsId(all[0].id);
    } else {
      setSettings({ userId: user.id, enabled: false, selectedTone: "Cosmic", generationCount: 0 });
    }
    setLoading(false);
  };

  const save = async (patch) => {
    const merged = { ...settings, ...patch };
    setSettings(merged);
    if (settingsId) {
      await base44.entities.NFTAutoMakeSettings.update(settingsId, patch);
    } else {
      const created = await base44.entities.NFTAutoMakeSettings.create({ ...merged });
      setSettingsId(created.id);
    }
  };

  const handleToggle = async () => {
    if (!settings.selectedTone && !settings.enabled) {
      alert("Please select a tone before enabling Auto-Make.");
      return;
    }
    await save({ enabled: !settings.enabled });
  };

  const handleGenerate = async () => {
    if (!settings?.selectedTone) return;
    setGenerating(true);

    const prompt = TONE_PROMPTS[settings.selectedTone];
    const nftName = `${settings.selectedTone} Genesis #${(settings.generationCount || 0) + 1}`;
    const rarity = weightedRarity();

    const { url: imageUrl } = await base44.integrations.Core.GenerateImage({ prompt });
    const dnaSequence = generateDNA(nftName + user.id);
    const byteId = generateByteId(nftName + user.id + Date.now());

    await base44.entities.NFTs.create({
      name: nftName,
      description: `Auto-generated by Quanti AI in ${settings.selectedTone} tone.`,
      price: parseFloat((Math.random() * 100).toFixed(2)),
      rarity,
      imageUrl,
      dnaSequence,
      byteId,
      frequency: parseFloat((432 + Math.random() * 96).toFixed(2)),
      coherence: parseFloat((70 + Math.random() * 30).toFixed(2)),
      createdBy: user.id,
      owner: user?.full_name || user?.email || "Unknown",
      autoGenerated: true,
      quantiTone: settings.selectedTone,
      listed: true,
      mintTime: new Date().toISOString(),
      tokenId: `QVTX-Q-${Date.now()}`,
    });

    await save({ generationCount: (settings.generationCount || 0) + 1, lastGeneratedAt: new Date().toISOString() });
    setGenerating(false);
    onGenerated?.();
  };

  if (loading) return <div className="h-10 animate-pulse bg-white/5 rounded-xl" />;

  return (
    <div className="bg-[#0d0e16] border border-purple-500/20 rounded-2xl p-6 space-y-5">
      {/* Header + toggle */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-400" />
            Quanti Auto-Make
          </h3>
          <p className="text-xs text-white/40 mt-0.5">Let Quanti AI generate NFTs for you automatically</p>
        </div>
        <button
          onClick={handleToggle}
          className={`relative w-12 h-6 rounded-full transition-colors duration-300 ${settings?.enabled ? "bg-purple-500" : "bg-white/10"}`}
        >
          <span
            className={`absolute top-0.5 left-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform duration-300 ${settings?.enabled ? "translate-x-6" : ""}`}
          />
        </button>
      </div>

      {/* Tone selector */}
      <div>
        <p className="text-xs text-white/40 mb-2">Generation Tone</p>
        <div className="grid grid-cols-1 sm:grid-cols-5 gap-2">
          {TONES.map(t => (
            <button
              key={t.name}
              onClick={() => save({ selectedTone: t.name })}
              className={`flex flex-col items-center gap-1 px-2 py-3 rounded-xl border text-center transition-all ${
                settings?.selectedTone === t.name
                  ? "border-purple-500/60 bg-purple-500/10"
                  : "border-white/5 bg-black/20 hover:border-white/20"
              }`}
            >
              <span className="text-xl">{t.icon}</span>
              <span className="text-xs font-bold text-white">{t.name}</span>
              <span className="text-[10px] text-white/30 leading-tight">{t.desc}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Stats row */}
      <div className="flex items-center justify-between text-xs text-white/30 border-t border-white/5 pt-4">
        <span>Generated: <span className="text-purple-300 font-bold">{settings?.generationCount || 0}</span></span>
        {settings?.lastGeneratedAt && (
          <span>Last: {new Date(settings.lastGeneratedAt).toLocaleDateString()}</span>
        )}
        <span className={`px-2 py-0.5 rounded-full font-semibold ${settings?.enabled ? "bg-purple-500/20 text-purple-300" : "bg-white/5 text-white/30"}`}>
          {settings?.enabled ? "ACTIVE" : "INACTIVE"}
        </span>
      </div>

      {/* Manual generate button */}
      <button
        onClick={handleGenerate}
        disabled={generating || !settings?.selectedTone}
        className="w-full py-2.5 rounded-xl font-bold text-sm flex items-center justify-center gap-2 disabled:opacity-50 transition-all"
        style={{ background: "linear-gradient(135deg, #7c3aed44, #a855f744)", border: "1px solid rgba(168,85,247,0.3)", color: "#c4b5fd" }}
      >
        {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />}
        {generating ? "Generating..." : "Generate Now"}
      </button>
    </div>
  );
}