import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Upload, Loader2, Sparkles, X } from "lucide-react";
import RarityBadge, { RARITIES } from "./RarityBadge";

const TONES = ["Cosmic", "Bio-Digital", "Cyber-Punk", "Quantum", "Abstract"];

function generateDNA(seed = "") {
  const bases = "ATCG";
  let dna = "";
  const hash = [...seed].reduce((a, c) => a + c.charCodeAt(0), Date.now());
  for (let i = 0; i < 32; i++) {
    dna += bases[(hash * (i + 1) * 31337) % 4 | 0];
  }
  return dna;
}

function generateByteId(name = "", userId = "") {
  const str = name + userId + Date.now();
  let h = 0xdeadbeef;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 2654435761);
  }
  return "0x" + ((h >>> 0).toString(16).padStart(8, "0")).toUpperCase();
}

export default function CreateNFTForm({ user, onCreated, onCancel }) {
  const [form, setForm] = useState({
    name: "",
    description: "",
    price: "",
    rarity: "COMMON",
    imageFile: null,
    imagePreview: null,
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  const handleImage = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    set("imageFile", file);
    const reader = new FileReader();
    reader.onload = (ev) => set("imagePreview", ev.target.result);
    reader.readAsDataURL(file);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.name.trim()) { setError("Name is required."); return; }
    setLoading(true);
    setError(null);

    let imageUrl = null;
    if (form.imageFile) {
      const { file_url } = await base44.integrations.Core.UploadFile({ file: form.imageFile });
      imageUrl = file_url;
    }

    const dnaSequence = generateDNA(form.name + user?.id);
    const byteId = generateByteId(form.name, user?.id);
    const frequency = parseFloat((432 + Math.random() * 96).toFixed(2));
    const coherence = parseFloat((60 + Math.random() * 40).toFixed(2));

    await base44.entities.NFTs.create({
      name: form.name,
      description: form.description,
      price: parseFloat(form.price) || 0,
      rarity: form.rarity,
      imageUrl,
      dnaSequence,
      byteId,
      frequency,
      coherence,
      createdBy: user?.id,
      owner: user?.full_name || user?.email || "Unknown",
      autoGenerated: false,
      listed: true,
      mintTime: new Date().toISOString(),
      tokenId: `QVTX-${Date.now()}`,
    });

    setLoading(false);
    onCreated?.();
  };

  return (
    <div className="bg-[#0d0e16] border border-white/10 rounded-2xl p-6 max-w-lg w-full">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-lg font-bold text-white flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-cyan-400" />
          Create NFT
        </h2>
        {onCancel && (
          <button onClick={onCancel} className="text-white/40 hover:text-white">
            <X className="w-5 h-5" />
          </button>
        )}
      </div>

      {error && <p className="text-rose-400 text-sm mb-4 bg-rose-500/10 px-3 py-2 rounded-lg">{error}</p>}

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Image upload */}
        <div>
          <label className="block text-xs text-white/40 mb-2">Artwork Image</label>
          <label className="flex flex-col items-center justify-center w-full h-36 border-2 border-dashed border-white/10 rounded-xl cursor-pointer hover:border-cyan-500/40 transition-colors relative overflow-hidden bg-black/20">
            {form.imagePreview ? (
              <img src={form.imagePreview} className="absolute inset-0 w-full h-full object-cover" alt="preview" />
            ) : (
              <div className="flex flex-col items-center gap-2 text-white/30">
                <Upload className="w-7 h-7" />
                <span className="text-xs">Click to upload</span>
              </div>
            )}
            <input type="file" accept="image/*" className="hidden" onChange={handleImage} />
          </label>
        </div>

        <div>
          <label className="block text-xs text-white/40 mb-1">Name *</label>
          <input
            value={form.name}
            onChange={e => set("name", e.target.value)}
            placeholder="My QVTX NFT"
            className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-white/20 focus:outline-none focus:border-cyan-500/50"
          />
        </div>

        <div>
          <label className="block text-xs text-white/40 mb-1">Description</label>
          <textarea
            value={form.description}
            onChange={e => set("description", e.target.value)}
            placeholder="Describe your NFT..."
            rows={3}
            className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-white/20 focus:outline-none focus:border-cyan-500/50 resize-none"
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs text-white/40 mb-1">Price (QVTX)</label>
            <input
              type="number"
              min="0"
              step="0.01"
              value={form.price}
              onChange={e => set("price", e.target.value)}
              placeholder="0.00"
              className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-white/20 focus:outline-none focus:border-cyan-500/50"
            />
          </div>
          <div>
            <label className="block text-xs text-white/40 mb-1">Rarity</label>
            <select
              value={form.rarity}
              onChange={e => set("rarity", e.target.value)}
              className="w-full bg-black/30 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-cyan-500/50"
            >
              {RARITIES.map(r => <option key={r} value={r}>{r}</option>)}
            </select>
          </div>
        </div>

        {/* Rarity preview */}
        <div className="flex items-center gap-2 px-3 py-2 bg-black/20 rounded-xl">
          <span className="text-xs text-white/30">Selected rarity:</span>
          <RarityBadge rarity={form.rarity} />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full py-3 rounded-xl font-bold text-black text-sm flex items-center justify-center gap-2 disabled:opacity-60"
          style={{ background: "linear-gradient(135deg, #00d4ff, #ffd700)" }}
        >
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          {loading ? "Minting..." : "Mint NFT"}
        </button>
      </form>
    </div>
  );
}