import React from "react";
import { Link } from "react-router-dom";
import { Sparkles, Cpu, Tag } from "lucide-react";
import RarityBadge, { getRarityConfig } from "./RarityBadge";
import DNAHelix from "./DNAHelix";

export default function NFTCard({ nft }) {
  const cfg = getRarityConfig(nft.rarity);

  return (
    <Link
      to={`/NFTDetail?id=${nft.id}`}
      className="group block bg-[#0d0e16] border border-white/10 rounded-2xl overflow-hidden hover:border-opacity-60 transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl"
      style={{ "--accent": cfg.color, borderColor: `${cfg.color}22` }}
    >
      {/* Image */}
      <div className="relative aspect-square overflow-hidden bg-[#080910]">
        {nft.imageUrl ? (
          <img
            src={nft.imageUrl}
            alt={nft.name}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center" style={{ background: `radial-gradient(circle at 50% 50%, ${cfg.color}18, #080910)` }}>
            <div className="text-center">
              <div className="text-5xl font-orbitron font-black opacity-20" style={{ color: cfg.color }}>
                {nft.name?.charAt(0) || "?"}
              </div>
              <div className="text-xs text-white/20 mt-2 font-mono">No Image</div>
            </div>
          </div>
        )}

        {/* Auto-generated badge */}
        {nft.autoGenerated && (
          <div className="absolute top-2 left-2 flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-semibold bg-black/60 backdrop-blur-sm border border-purple-500/30 text-purple-300">
            <Sparkles className="w-3 h-3" />
            Quanti
          </div>
        )}

        {/* Price tag */}
        {nft.price > 0 && (
          <div className="absolute top-2 right-2 flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-bold bg-black/60 backdrop-blur-sm border border-emerald-500/30 text-emerald-300">
            <Tag className="w-3 h-3" />
            {nft.price} QVTX
          </div>
        )}

        {/* Bottom DNA strip overlay */}
        <div className="absolute bottom-0 left-0 right-0 px-3 py-2 bg-gradient-to-t from-black/80 to-transparent">
          <DNAHelix dnaSequence={nft.dnaSequence} color1={cfg.color} color2="#f472b6" height={28} />
        </div>
      </div>

      {/* Info */}
      <div className="p-4">
        <div className="flex items-start justify-between gap-2 mb-2">
          <h3 className="font-bold text-white text-sm leading-snug line-clamp-1">{nft.name}</h3>
          <RarityBadge rarity={nft.rarity} />
        </div>

        {nft.byteId && (
          <div className="flex items-center gap-1 mb-2">
            <Cpu className="w-3 h-3 text-cyan-500/50" />
            <span className="text-xs font-mono text-white/30 truncate">{nft.byteId}</span>
          </div>
        )}

        <div className="flex items-center justify-between text-xs text-white/30 mt-2 pt-2 border-t border-white/5">
          <span>Coherence: <span className="text-white/60">{nft.coherence?.toFixed(1) ?? "—"}</span></span>
          <span>{nft.frequency ? `${nft.frequency} Hz` : ""}</span>
        </div>
      </div>
    </Link>
  );
}