import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { motion } from "framer-motion";
import { Sparkles, Plus, X, Layers, DollarSign, Star } from "lucide-react";
import NFTCard from "@/components/nft/NFTCard";
import CreateNFTForm from "@/components/nft/CreateNFTForm";
import AutoMakePanel from "@/components/nft/AutoMakePanel";
import RarityBadge, { getRarityConfig } from "@/components/nft/RarityBadge";
import { useAuth } from "@/lib/AuthContext";

const RARITY_ORDER = { MYTHIC: 5, LEGENDARY: 4, EPIC: 3, RARE: 2, COMMON: 1 };

export default function MyNFTs() {
  const { user, isAuthenticated } = useAuth();
  const [nfts, setNfts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [tab, setTab] = useState("all");

  useEffect(() => {
    if (isAuthenticated && user?.id) load();
  }, [isAuthenticated, user?.id]);

  const load = async () => {
    setLoading(true);
    const data = await base44.entities.NFTs.filter({ createdBy: user.id });
    setNfts(data);
    setLoading(false);
  };

  if (!isAuthenticated) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-6">
        <Sparkles className="w-14 h-14 text-cyan-400/40" />
        <p className="text-white/40 text-lg">Please log in to access your NFT dashboard</p>
        <button
          onClick={() => base44.auth.redirectToLogin(window.location.href)}
          className="px-6 py-3 rounded-xl font-bold text-black"
          style={{ background: "linear-gradient(135deg, #00d4ff, #ffd700)" }}
        >
          Login / Sign Up
        </button>
      </div>
    );
  }

  // Stats
  const totalValue = nfts.reduce((s, n) => s + (n.price || 0), 0);
  const rarityCounts = nfts.reduce((acc, n) => { acc[n.rarity] = (acc[n.rarity] || 0) + 1; return acc; }, {});
  const autoNFTs = nfts.filter(n => n.autoGenerated);
  const manualNFTs = nfts.filter(n => !n.autoGenerated);

  const tabNFTs = tab === "all" ? nfts : tab === "manual" ? manualNFTs : autoNFTs;

  return (
    <div className="px-4 sm:px-6 lg:px-8 py-8 min-h-screen">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-3xl font-orbitron font-bold text-white" style={{ textShadow: "0 0 20px rgba(0,212,255,0.35)" }}>
              My NFTs
            </h1>
            <p className="text-white/40 text-sm mt-1">{user?.full_name || user?.email}</p>
          </div>
          <button
            onClick={() => setShowCreate(true)}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-bold text-black text-sm"
            style={{ background: "linear-gradient(135deg, #00d4ff, #ffd700)" }}
          >
            <Plus className="w-4 h-4" />
            Create NFT
          </button>
        </div>

        {/* Create form modal */}
        {showCreate && (
          <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <CreateNFTForm user={user} onCreated={() => { setShowCreate(false); load(); }} onCancel={() => setShowCreate(false)} />
          </div>
        )}

        {/* Stats row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Total NFTs", value: nfts.length, icon: <Layers className="w-5 h-5" />, color: "#00d4ff" },
            { label: "Total Value", value: `${totalValue.toFixed(2)} QVTX`, icon: <DollarSign className="w-5 h-5" />, color: "#ffd700" },
            { label: "Manual NFTs", value: manualNFTs.length, icon: <Plus className="w-5 h-5" />, color: "#10b981" },
            { label: "Quanti Generated", value: autoNFTs.length, icon: <Sparkles className="w-5 h-5" />, color: "#a78bfa" },
          ].map(s => (
            <motion.div
              key={s.label}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-[#0d0e16] border border-white/10 rounded-2xl p-4 flex items-center gap-3"
              style={{ borderColor: `${s.color}22` }}
            >
              <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0" style={{ background: `${s.color}18` }}>
                <span style={{ color: s.color }}>{s.icon}</span>
              </div>
              <div>
                <p className="text-xs text-white/40">{s.label}</p>
                <p className="text-lg font-bold font-orbitron" style={{ color: s.color }}>{s.value}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Rarity breakdown */}
        {nfts.length > 0 && (
          <div className="bg-[#0d0e16] border border-white/10 rounded-2xl p-5">
            <p className="text-xs text-white/40 uppercase tracking-widest mb-3">Rarity Breakdown</p>
            <div className="flex flex-wrap gap-3">
              {Object.entries(rarityCounts).sort((a, b) => (RARITY_ORDER[b[0]] || 0) - (RARITY_ORDER[a[0]] || 0)).map(([rarity, count]) => (
                <div key={rarity} className="flex items-center gap-2">
                  <RarityBadge rarity={rarity} />
                  <span className="text-sm font-bold text-white/60">×{count}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Auto-Make panel */}
        <AutoMakePanel user={user} onGenerated={load} />

        {/* NFT Tabs */}
        <div>
          <div className="flex items-center gap-2 mb-5">
            {[
              { key: "all", label: `All (${nfts.length})` },
              { key: "manual", label: `Created (${manualNFTs.length})` },
              { key: "auto", label: `Quanti (${autoNFTs.length})` },
            ].map(t => (
              <button
                key={t.key}
                onClick={() => setTab(t.key)}
                className={`px-4 py-2 rounded-xl text-sm font-semibold transition-all ${
                  tab === t.key
                    ? "bg-cyan-500/15 border border-cyan-500/40 text-cyan-300"
                    : "bg-white/5 border border-white/10 text-white/40 hover:text-white/70"
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          {loading ? (
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {Array(8).fill(0).map((_, i) => <div key={i} className="aspect-square bg-white/5 rounded-2xl animate-pulse" />)}
            </div>
          ) : tabNFTs.length === 0 ? (
            <div className="text-center py-16">
              <Sparkles className="w-10 h-10 text-white/10 mx-auto mb-3" />
              <p className="text-white/30">No NFTs here yet</p>
              <button
                onClick={() => setShowCreate(true)}
                className="mt-4 px-5 py-2 rounded-xl font-bold text-black text-sm"
                style={{ background: "linear-gradient(135deg, #00d4ff, #ffd700)" }}
              >
                Mint Your First NFT
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              {tabNFTs.map((nft, i) => (
                <motion.div key={nft.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}>
                  <NFTCard nft={nft} />
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}