import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Cpu, Sparkles, Tag, Copy, CheckCheck, ExternalLink, Zap, Activity, User } from "lucide-react";
import RarityBadge, { getRarityConfig } from "@/components/nft/RarityBadge";
import DNAHelix from "@/components/nft/DNAHelix";
import { useAuth } from "@/lib/AuthContext";

function CopyBtn({ text }) {
  const [copied, setCopied] = useState(false);
  if (!text) return null;
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
      className="ml-2 text-white/30 hover:text-cyan-400 transition-colors"
    >
      {copied ? <CheckCheck className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
    </button>
  );
}

export default function NFTDetail() {
  const [nft, setNft] = useState(null);
  const [loading, setLoading] = useState(true);
  const { user, isAuthenticated } = useAuth();

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    if (id) load(id);
  }, []);

  const load = async (id) => {
    setLoading(true);
    const data = await base44.entities.NFTs.filter({ id });
    setNft(data[0] || null);
    setLoading(false);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="w-8 h-8 border-4 border-cyan-500/20 border-t-cyan-500 rounded-full animate-spin" />
      </div>
    );
  }

  if (!nft) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <p className="text-white/40 text-lg">NFT not found</p>
        <Link to="/NFTGallery" className="text-cyan-400 hover:underline flex items-center gap-1">
          <ArrowLeft className="w-4 h-4" /> Back to Gallery
        </Link>
      </div>
    );
  }

  const cfg = getRarityConfig(nft.rarity);
  const isOwner = isAuthenticated && user?.id === nft.createdBy;

  const metrics = [
    { label: "Frequency", value: nft.frequency ? `${nft.frequency} Hz` : "—", icon: <Activity className="w-4 h-4" />, color: "#00d4ff" },
    { label: "Coherence", value: nft.coherence ? `${nft.coherence.toFixed(1)}%` : "—", icon: <Zap className="w-4 h-4" />, color: "#ffd700" },
    { label: "Price", value: nft.price ? `${nft.price} QVTX` : "Not listed", icon: <Tag className="w-4 h-4" />, color: "#10b981" },
  ];

  return (
    <div className="px-4 sm:px-6 lg:px-8 py-8 min-h-screen">
      <div className="max-w-5xl mx-auto">
        {/* Back nav */}
        <Link
          to="/NFTGallery"
          className="inline-flex items-center gap-2 text-sm text-white/40 hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Gallery
        </Link>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left: image */}
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
            <div
              className="relative rounded-3xl overflow-hidden aspect-square"
              style={{ border: `2px solid ${cfg.color}44`, boxShadow: `0 0 60px ${cfg.color}22` }}
            >
              {nft.imageUrl ? (
                <img src={nft.imageUrl} alt={nft.name} className="w-full h-full object-cover" />
              ) : (
                <div className="w-full h-full flex items-center justify-center" style={{ background: `radial-gradient(circle, ${cfg.color}18, #080910)` }}>
                  <span className="text-8xl font-orbitron font-black opacity-20" style={{ color: cfg.color }}>
                    {nft.name?.charAt(0) || "?"}
                  </span>
                </div>
              )}

              {/* Auto badge */}
              {nft.autoGenerated && (
                <div className="absolute top-4 left-4 flex items-center gap-1.5 px-3 py-1 rounded-full bg-black/70 backdrop-blur-sm border border-purple-500/40 text-purple-300 text-xs font-bold">
                  <Sparkles className="w-3.5 h-3.5" />
                  Generated by Quanti {nft.quantiTone && `· ${nft.quantiTone}`}
                </div>
              )}

              {/* DNA strip at bottom */}
              <div className="absolute bottom-0 left-0 right-0 px-4 py-3 bg-gradient-to-t from-black/90 to-transparent">
                <DNAHelix dnaSequence={nft.dnaSequence} color1={cfg.color} color2="#f472b6" height={36} />
              </div>
            </div>
          </motion.div>

          {/* Right: details */}
          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="space-y-5">
            {/* Title + rarity */}
            <div>
              <div className="flex items-center gap-3 mb-2">
                <RarityBadge rarity={nft.rarity} size="lg" />
                {nft.tokenId && (
                  <span className="text-xs font-mono text-white/30">{nft.tokenId}</span>
                )}
              </div>
              <h1 className="text-3xl font-orbitron font-black text-white leading-tight" style={{ textShadow: `0 0 30px ${cfg.color}40` }}>
                {nft.name}
              </h1>
              {nft.description && (
                <p className="text-white/50 text-sm mt-2 leading-relaxed">{nft.description}</p>
              )}
            </div>

            {/* Metrics */}
            <div className="grid grid-cols-3 gap-3">
              {metrics.map(m => (
                <div key={m.label} className="bg-[#0d0e16] border border-white/10 rounded-xl p-3 text-center" style={{ borderColor: `${m.color}22` }}>
                  <div className="flex justify-center mb-1" style={{ color: m.color }}>{m.icon}</div>
                  <p className="text-xs text-white/30 mb-0.5">{m.label}</p>
                  <p className="text-sm font-bold" style={{ color: m.color }}>{m.value}</p>
                </div>
              ))}
            </div>

            {/* ByteID */}
            {nft.byteId && (
              <div className="bg-[#0d0e16] border border-cyan-500/15 rounded-xl p-4">
                <div className="flex items-center gap-2 mb-1">
                  <Cpu className="w-4 h-4 text-cyan-500" />
                  <span className="text-xs text-white/40">ByteID</span>
                </div>
                <div className="flex items-center gap-1">
                  <span className="font-mono text-cyan-300 text-sm">{nft.byteId}</span>
                  <CopyBtn text={nft.byteId} />
                </div>
              </div>
            )}

            {/* DNA Sequence */}
            {nft.dnaSequence && (
              <div className="bg-[#0d0e16] border border-emerald-500/15 rounded-xl p-4">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs text-white/40">DNA Sequence</span>
                  <CopyBtn text={nft.dnaSequence} />
                </div>
                <p className="font-mono text-xs text-emerald-300/80 break-all leading-relaxed">{nft.dnaSequence}</p>
                <div className="mt-3">
                  <DNAHelix dnaSequence={nft.dnaSequence} color1={cfg.color} color2="#f472b6" height={44} />
                </div>
              </div>
            )}

            {/* Owner info */}
            <div className="bg-[#0d0e16] border border-white/5 rounded-xl p-4 flex items-center gap-3">
              <div className="w-9 h-9 rounded-full bg-white/10 flex items-center justify-center flex-shrink-0">
                <User className="w-4 h-4 text-white/50" />
              </div>
              <div>
                <p className="text-xs text-white/30">Owner</p>
                <p className="text-sm font-semibold text-white">{nft.owner || "Unknown"}</p>
              </div>
              {nft.mintTime && (
                <div className="ml-auto text-right">
                  <p className="text-xs text-white/30">Minted</p>
                  <p className="text-xs text-white/50">{new Date(nft.mintTime).toLocaleDateString()}</p>
                </div>
              )}
            </div>

            {/* CTA */}
            <div className="flex gap-3">
              {isOwner ? (
                <Link
                  to="/MyNFTs"
                  className="flex-1 py-3 rounded-xl font-bold text-center text-sm border border-white/20 text-white/60 hover:bg-white/5 transition-all"
                >
                  View in My Collection
                </Link>
              ) : (
                <button
                  className="flex-1 py-3 rounded-xl font-bold text-black text-sm"
                  style={{ background: `linear-gradient(135deg, ${cfg.color}, #ffd700)` }}
                >
                  {nft.price ? `Buy for ${nft.price} QVTX` : "Make Offer"}
                </button>
              )}
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}